# Generated by Django 5.0.2 on 2024-03-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.tag', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
